### ISSUE TITLE
Checking whether the Trailblazer is already installed

### ISSUE THREAD

**Issue by mattkennedynz** [twingl/trailblazer-website#8]
Hey @glsignal, in a blurred haze I've largely axed our MailChimp subscription (saving $$$ in the process each month). But then I had a "oh shit" moment when I realised we have MailChimp forms on the landing page.

So I said "fuck it" and started to do the thing. The thing being removing the MailChimp forms and attempting to add an inline install button. To my credit, it's [actually working-ish](http://trailblazer.io/#install). The case which isn't being handled as I would like is _"website visitor has Trailblazer already installed."_

Following [https://developer.chrome.com/webstore/inline_installation#already-installed](https://developer.chrome.com/webstore/inline_installation#already-installed), I thought this test would be trivial. But running chrome.app.isInstalled from the Chrome console, it's coming up false despite me having the Trailblazer extension installed.

Can your eagle eyes see where I might be going wrong? This isn't urgent, as at least we have a big green working button (as well as a "Chrome Required" message functioning for other browsers). But it's one of those details I'm eager to see if we can get functioning.

The annoying thing is that this is hard to test outside of production. The links and things only work when the code is being hosted from trailblazer.io (but you could do a hosts work around, I suppose?)

**Comment by glsignal** [comment]
In the past I've had trouble with the same thing - I can take a look this evening.

**Comment by mattkennedynz** [comment]
Ah wonderful, thanks dude!

**Comment by glsignal** [comment]
Ah yes, confusingly this is not meant for _all_ extensions. Trailblazer will need a minor change in order to support this kind of feature (injecting a node on the page)

See https://bugs.chromium.org/p/chromium/issues/detail?id=129960
